### ISSUE TITLE
Adding Products

### ISSUE THREAD

**Issue by dpanayotov93** [dpanayotov93/VB-Automation#10]
The admin should be able to add products

**Comment by db4e** [comment]
Add product functionality added in [commit 04b597a](https://github.com/dpanayotov93/VB-Automation/commit/04b597a01048ecae3feb1098feebf089e14683f1).
Expectations:
* Much bugs
* Very not working

Guide on how to:

**Adding products with addProduct option.**
  
**I. Получавена на нужните полета за добавяне на продукт в дадена категория**
* Заявка:
  * **q=addProduct**
  * **catid=*****[id на категория]***
* Връща:
  * status.type = success/error

**II. Добавяне на продукт**
* Заявка:
  * **q=addProduct**
  * **catid=*****[id на категория]***
  * Попълнени получените полета:
    * **имена и описания на всички езици**
	* **imgurl=*****[линк към снимка]***
	* **получени съответните свойства за дадения продукт**
	  * **NOTE**: Може да се записват празни полета.
* Връща:
  * status.type = success/error
  
**III. Получаване на всички продукти**
* Заявка:
  * **q=addProduct**
  * ако има **deleted=1** показва само изтритите продукти
  * ако има **catid=*****[id на категория]*** показва само продукти от дадена категория
* Връща:
  * JSON обект със избраните продукти и техните параметри

**IV. Получаване на един продукт**
* Заявка:
  * **q=addProduct**
  * **show=1**
  * **id=*****[id на продукт]***
* Връща:
  * JSON обект със избрания обект и неговите параметри

**Comment by db4e** [comment]
Adding products looks to be working fine so far.
Will leave the issue open for one more week of tests.
