### ISSUE TITLE
Editing Products

### ISSUE THREAD

**Issue by dpanayotov93** [dpanayotov93/VB-Automation#11]
The admin should be able to edit the products

**Comment by db4e** [comment]
Add product functionality added in [commit 04b597a](https://github.com/dpanayotov93/VB-Automation/commit/04b597a01048ecae3feb1098feebf089e14683f1).
Expectations:
* Much bugs
* Very not working

Guide on how to:

**Editing products with addProduct option.**
  
**I. Обновяване на продукт**
* Заявка:
  * **q=addProduct**
  * **id=*****[id на продукт]***
  * Попълнени получените полета:
    * **имена и описания на всички езици**
	* **imgurl=*****[линк към снимка]***
	* **получени съответните свойства за дадения продукт**
	  * **NOTE**: Може да се записват празни полета.
	  * **NOTE**: Стойностите не се обновяват само ако **не** се подаде заявка със съответното поле.
* Връща:
  * status.type = success/error

**III. Получаване на всички продукти**
* Заявка:
  * **q=addProduct**
  * ако има **deleted=1** показва само изтритите продукти
  * ако има **catid=*****[id на категория]*** показва само продукти от дадена категория
* Връща:
  * JSON обект със избраните продукти и техните параметри

**IV. Получаване на един продукт**
* Заявка:
  * **q=addProduct**
  * **show=1**
  * **id=*****[id на продукт]***
* Връща:
  * JSON обект със избрания обект и неговите параметри

**Comment by db4e** [comment]
Clicking edit on a product shows a blank edit form with no fields or buttons.

**Comment by db4e** [comment]
Attaching console log.
When pressing the 'Edit' button:
> Uncaught TypeError: adminController.editProduct is not a functiononclick @ (index):1
When pressing the Save changes button:
> Uncaught TypeError: adminController.sendEditedProduct is not a functiononclick @ (index):1
