### ISSUE TITLE
Removing Products

### ISSUE THREAD

**Issue by dpanayotov93** [dpanayotov93/VB-Automation#12]
The admin should be able to remove products

**Comment by db4e** [comment]
Add product functionality added in [commit 04b597a](https://github.com/dpanayotov93/VB-Automation/commit/04b597a01048ecae3feb1098feebf089e14683f1).
Expectations:
* Much bugs
* Very not working

Guide on how to:

**Deleting products with addProduct option.**
  

**I. Изтриване/скриване на продукт**
* Заявка:
  * **q=addProduct**
  * **id=*****[id на продукт]***
  * **delete=1**
* Връща:
  * status.type = success/error

**II. Възтановяване/позакване на скрит продукт**
* Заявка:
  * **q=addProduct**
  * **id=*****[id на продукт]***
  * **restore=1**
* Връща:
  * status.type = success/error

**III. Получаване на всички продукти**
* Заявка:
  * **q=addProduct**
  * ако има **deleted=1** показва само изтритите продукти
  * ако има **catid=*****[id на категория]*** показва само продукти от дадена категория
* Връща:
  * JSON обект със избраните продукти и техните параметри

**Comment by db4e** [comment]
After clicking the X button to remove a product nothing happens.
If a php/database but a debug log is needed.

**Comment by db4e** [comment]
It works now...

Still... there is no way to undo/recover deleted products.
