### ISSUE TITLE
Editing Categories

### ISSUE THREAD

**Issue by dpanayotov93** [dpanayotov93/VB-Automation#14]
The admin should be to edit categories

**Comment by db4e** [comment]
Info on Editing categories will be provided on 25.12.

**Comment by db4e** [comment]
Editing categories does not work at all. 
The edit window is shown but after edit nothing is changed.

If php/database issue a debug log is needed.

**Comment by db4e** [comment]
Editing now works as expected.

To be done:
* After edit the page remains darker even after the edit window disappears.
* The parent ID should be editable the same way as when adding categories.
