### ISSUE TITLE
Additional Products Properties

### ISSUE THREAD

**Issue by dpanayotov93** [dpanayotov93/VB-Automation#19]
The products should have NAME and PRICE properties as well.
Add "name" as the first property, set "imgURL" (or whatever is the name for the product image url) as second property, the set the rest and finally set "price" as the last one.

**Comment by db4e** [comment]
Somewhat fix with [commit 883aa83 (Bugfixes and patch for issue 19)](https://github.com/dpanayotov93/VB-Automation/commit/883aa8390538bc20ba36e6dce0ace8f2805f1ee3).
It returns values as requested but product page looks broken.
Example of return value:
{"name":"sensor","Image":"https:\/\/www.ifm.com\/tedo\/foto\/400_0033.gif","system":"Incremental encoders","design":"hollow shaft encoder","resolution":">100 to 300","shaft":"6 mm","output":"SSI","features":"IO-Link interface","bit":"24","type":"RO (58 mm)","connection":"Cable","approval":"e1","price":"4.2"}

**Comment by dpanayotov93** [comment]
Thank you
