### ISSUE TITLE
Adding properties for categories

### ISSUE THREAD

**Issue by db4e** [dpanayotov93/VB-Automation#20]
Need an admin page to add/edit/delete properties for categories.
Once the the property management page is done we can proceed to adding an admin page for category editing.

**Comment by db4e** [comment]
**Working with addProperties option.
Adding categories and products will work the same way.**

**Short explanation:** 
1. JS sends request for fields to PHP
2. PHP returns field names to JS
3. JS sends filled fields to PHP

**Full explanation:**

**I. Получаване на полета за добавяне на свойства**
* Заявка:
  * **q=addProperty**
* Връща:
  * Списък с имена на инпути, които трябва да съдържа (за всички налични езици)
  * Ключът на всяка променлива е наименованието, което трябва да се изписва за ствойството.
  * Стойността е името на input-a, който трябва да се прати по POST. (може да се разменят или да се направят по друг начини, така е с най-малко изпращане на данни)
  * "addProperty":[{"Unique name":"name"},{"Name EN":"nameEN"},{"Discription EN":"descEN"},{"Appears in filters":"searchable"},{"Differs in languages":"langDependant"}]


**II. Добавяне на свойство**
* Заявка:
  * **q=addProperty**
  * Попълнени получените полета. (**Уникално име** + **имена и описания на всички езици** + **searchable** + **languageDependant**) 
    * *Може да има празни полета, но не е хубаво*
    * *SEARCHABLE и languageDependant са bool -> ползвай checkbox*
* Връща:
  * status.type = success/error
	
**III. Получаване на всички свойства**
* Заявка:
  * **q=addProperty**
  * **showProps=1**
  * ако има **deleted=1** показва изтритите свойства
* Връща:
  * JSON обект със всички свойства и техните параметри.


**IV. Обновяване на свойство**
* Заявка:
  * **q=addProperty**
  * **id=*****[id на продукт]***
  * Попълнени получените полета. (**Уникално име** + **имена и описания на всички езици** + **searchable** + **languageDependant**) 
    * *Може да има празни полета*
* Връща:
  * status.type = success/error

**V. Изтриване/скриване на свойство**
* Заявка:
  * **q=addProperty**
  * **delete=1**
* Връща:
  * status.type = success/error

**VI. Възтановяване/позакване на скрито свойство**
* Заявка:
  * **q=addProperty**
  * **restore=1**
* Връща:
  * status.type = success/error

**Comment by dpanayotov93** [comment]
Everything is implemented

**Comment by dpanayotov93** [comment]
I must first fix the "Editing" option. Because it's broken and I will close the issue. I believe that it's a minor bug.

**Comment by dpanayotov93** [comment]
Done

**Comment by db4e** [comment]
There are several issues around editing properties:
* Unique name should not be available for edit.
* Language dependent should not be editable for now.
* The check boxes (for language and filter visibility) can only be set to **one **not and not to **zero**.
* After completing the edit the screen freezes and needs a refresh.
* There is not option to see/undo deleted items (undo button after delete would be nice).
