### ISSUE TITLE
Favorites

### ISSUE THREAD

**Issue by dpanayotov93** [dpanayotov93/VB-Automation#6]
The favorites button must display the favorite orders page

**Comment by db4e** [comment]
Favorites can be products or categories.

To add favorite:
**q=favorites**
**userid=_user id_**
**add=1**
**productid=_product id_ OR category=_category id**

To delete favorite:
**q=favorites**
**userid=_user id_**
**remove=1**
**productid=_product id_ OR category=_category id**

To show existing favorites:
**q=favorites**
**userid=_user id_**
**products=1 - to show products**
**categories=1 - to show categories**
