### ISSUE TITLE
Adding promo codes

### ISSUE THREAD

**Issue by dpanayotov93** [dpanayotov93/VB-Automation#9]
The admin should be able to add promo code to Users

**Comment by db4e** [comment]
Info on adding/editing discounts:

1. Получаване на всички отстъпки
* Заявка:
  * q=addDiscount
* Връща:
  * "addDiscount":[{"discountid":"1","flat":"1","percent":"1","userid":"1","username":"mail@example.com","categoryid":"0","category":"*","productid":"0","product":"*"}]
  * status.type = error/success
 
2. Добавяне на отстъпка
* Заявка:
  * q=addDiscount
  * user = id на user
  * catid = id на категория
  * prodid = id на продукт
  * flat = плоска отстъпка И/ИЛИ percent = процент отстъпка
* Връща:
  * status.type = error/success
	 
3. Редактиране на отстъпка
* Заявка:
  * q=addDiscount
  * user = id на user
  * catid = id на категория
  * prodid = id на продукт
  * flat = плоска отстъпка И/ИЛИ percent = процент отстъпка
  * discountid = id на отстъпка
* Връща:
  * status.type = error/success
	 
4. Изтриване на отстъпка
* Заявка:
  * q=addDiscount
  * user = id на user
  * catid = id на категория
  * prodid = id на продукт
  * flat = плоска отстъпка И/ИЛИ percent = процент отстъпка
  * discountid = id на отстъпка
  * delete = нещо, няма значиене
	
  * *ДА, иска да са сложени всички параметри, макар да трие... ще го оправя някога :D*
* Връща:
  * status.type = error/success

**Comment by db4e** [comment]
Closed issue by mistake...
Reopening.
